### ISSUE TITLE
Spacetaxi image issues: Taxi shaking on acceleration, feature or bug?

### ISSUE THREAD

**Issue by Ulrik-dk** [diku-dk/DIKUArcade#30]
@alexpanter I am unsure as to whether or not the taxi animation shaking under acceleration is a feature or a bug. Due to unequal lengths of transparent space behind each taxisprite, the imagestride creation metehod makes some wierd cuts. This issue persists through the codec chance, since it is an issue with image dimensions.

To illustrate the issue, i have these two examples:

* Using the images from sortraev: https://vimeo.com/268948957
* Using some changes to dimensions (based on sortraev's changed files): https://vimeo.com/268948954

The changes consist of
* Adding 6 pixels pr. taxisprite to the canvas width of each imagefile, on the side of the file that went away from the taxi/taxis.
* Trimming one column of semitransparent pixels from the tip of the hindmost taxi of every image with two taxis.

If this is deemed a bug, and not a feature, ill gladly upload the zip with the new taxi sprites. I just want to avoid any semblance of plagiarism, in case the taxi is supposed to shake when it accelerates, which could be a plausible explaination.

(I opened this new issue, since i was unable to reopen the old one, and i was unsure if comments on closed issues would be seen. As such, i deleted the comment and posted the contents here instead.)

**Comment by alexpanter** [comment]
I am aware of the issue. You have manipulate the image and remove the superfluous pixels, or leave it as is. This will not affect the final grading. Someone might fix this image.

**Comment by Ulrik-dk** [comment]
Thanks!
[Images - fixed taxi.zip](https://github.com/diku-dk/DIKUArcade/files/1994621/Images.-.fixed.taxi.zip)
