### ISSUE TITLE
StaticTimer.Pause makes GameLoop come to standstill

### ISSUE THREAD

**Issue by tbdk** [diku-dk/DIKUArcade#33]
With commit ab7553672dcd24209676f5309f7e6b3fcbac56e4, calling StaticTimer.Pause, will make the GameLoop come to an effective standstill. Because GameTimer depends on StaticTimer, when the StaticTimer is paused, GameTimer.MeasureTime() measures no changes and GameTimer.ShouldUpdate() will never become true.

**Comment by alexpanter** [comment]
Thank you for posting. We are aware of this issue, and a solution will be commited later today.

**Comment by alexpanter** [comment]
Fixed in https://github.com/diku-dk/DIKUArcade/commit/95768ef9cbf50aa71f2bc6146ae8af44976a5219 .
